# Generated by Django 3.1.2 on 2020-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
