# Generated by Django 3.1.2 on 2020-10-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_vehicle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
