# Generated by Django 3.1.2 on 2020-10-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20201015_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reserved',
            field=models.CharField(choices=[('1', 'For Sale'), ('2', 'Reserved'), ('3', 'Sold')], default='2', max_length=8),
        ),
    ]
