# Generated by Django 3.1.2 on 2020-12-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20201015_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='mot_till',
            new_name='mot_expiry',
        ),
    ]
